# Brewfile - macOS 依赖（用 `brew bundle --file=Brewfile --no-lock` 安装）
brew "git"
brew "zsh"
brew "tmux"
brew "neovim"
brew "starship"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "zoxide"
brew "bat"
brew "eza"
brew "lazygit"
brew "git-delta"
brew "jq"
brew "gh"
